#!/usr/bin/perl
use lib 'lib';
use Gaiman;
use Data::Dumper;
use Getopt::Complete (
      'build'		=> [qw(personaje evento)],
      'log'			=> [qw(OFF FATAL ERROR WARN INFO DEBUG TRACE ALL)],
      'random!'		=> undef,
      'srand'		=> undef,
      'json!'		=> undef,
);

my %arg;
$arg{comando} = $ARGS{build};
$arg{random}  = $ARGS{random};
$arg{srand}  = $ARGS{srand};
$arg{json}    = $ARGS{json};
$arg{log}    = $ARGS{log} ? $ARGS{log} : q(OFF);

print Gaiman->instancia(\%arg)->runner(%arg);
print "\n";