#!/usr/bin/perl
use lib 'lib';
use Gaiman;
use Data::Dumper;
use Getopt::Complete (
      'build'		=> [qw(personaje evento)],
      'tipo'		=> [qw(BESAR)],
      'log'			=> [qw(OFF FATAL ERROR WARN INFO DEBUG TRACE ALL)],
      'random!'		=> undef,
      'srand'		=> undef,
      'json!'		=> undef,
      'detalle!'		=> undef,
);

my %arg;
$arg{build} = $ARGS{build};
$arg{tipo} = $ARGS{tipo};
$arg{random}  = $ARGS{random};
$arg{srand}  = $ARGS{srand};
$arg{json}    = $ARGS{json};
$arg{detalle}    = $ARGS{detalle};
$arg{log}    = $ARGS{log} ? $ARGS{log} : q(OFF);

print Gaiman->instancia({%arg})->runner({%arg});
print "\n";